sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t guwenjun2007/docker-react -f Dockerfile.dev .

script:
  - docker run guwenjun2007/docker-react npm run test -- --coverage

deplpy:
  # provider should be supported by travis
  provider: elasticbeanstalk
  # region should be the elasticbeanstalk region that you created in aws
  region: "us-west-2"
  # from aws UI
  app: "docker-react"
  # from aws UI
  env: "DockerReact-env"
  # from aws UI, autocreated in S3, bucket is used to save your src files
  bucket_name: "elasticbeanstalk-us-east-2-432727920151"
  # should be the same with app name
  bucket_path: "docker-react"
  on:
    #git branch
    branch: master
  #create an  user in IAM in AWS, then binding proper policy.
  # use the secret of the user so that you can act as the user
  # AWS_ACCESS_KEY and AWS_SECRET_KEY are set in travis environment variable.
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
