sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t guwenjun2007/docker-react -f Dockerfile.dev .

script:
  - docker run guwenjun2007/docker-react npm run test -- --coverage
